site_name: Tu luyện lịch sử
site_description: Khá nhiều thứ liên quan đến Lịch sử - địa lý trong nước lẫn thế giới.
site_author: duykhanh471

nav:
  - 'Trang chủ': index.md
  - 'Lịch sử Việt Nam':
    - 'Lộ trình lịch sử': 'qua-trinh-lich-su-viet-nam.md'
  - 'Lịch sử thế giới':
    - 'Châu Á': 'chau-a.md'
    - 'Châu Âu': 'chau-au.md'
    - 'Châu Phi': 'chau-phi.md'
    - 'Châu Mĩ': 'chau-mi.md'
  - 'Lịch sử cổ đại':
    - 'Ai Cập cổ đại': 'ai-cap-co-dai.md'
    - 'Hy Lạp cổ đại': 'hy-lap-co-dai.md'
    - 'Persia cổ đại': 'persia-co-dai.md'
    - 'Rome': 'rome.md'
    - 'Thời trung cổ': 'lich-su-trung-co.md'
  - 'Tài nguyên học': 'tai-nguyen-hoc.md'

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false
